language: java

services:
- mysql

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS ejercicio;'

install: true

jdk:
- oraclejdk8
- openjdk7

script: 
- mvn clean test

deploy:
  skip_cleanup: true
