language: java

jdk:
- oraclejdk8
- openjdk7

services:
  - mysql
  
sudo: true

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS ejercicio;'

install: true

before_script:
  - bash .travis.install-mysql-5.7.sh
  
script: 
- mvn clean test
